---
- raw: 'wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u20-b26/jdk-8u20-linux-x64.tar.gz" -O /tmp/jdk-8u20-linux-x64.tar.gz'
- raw: 'sudo tar xzf /tmp/jdk-8u20-linux-x64.tar.gz --directory=/usr/local/'
- raw: 'sudo update-alternatives --install "/usr/bin/java" "java" "/usr/local/jdk1.8.0_20/bin/java" 1'
- raw: 'sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/local/jdk1.8.0_20/bin/javac" 1'
- raw: 'sudo update-alternatives --install "/usr/bin/javaws" "javaws" "/usr/local/jdk1.8.0_20/bin/javaws" 1'
- raw: 'sudo update-alternatives --set "java" "/usr/local/jdk1.8.0_20/bin/java"'
- raw: 'sudo update-alternatives --set "javac" "/usr/local/jdk1.8.0_20/bin/javac"'
- raw: 'sudo update-alternatives --set "javaws" "/usr/local/jdk1.8.0_20/bin/javaws"'