---
- apt: pkg={{item}} state=present force=yes
  with_items:
    - icinga
    - icinga-web

- file: src=/etc/nagios3/conf.d/{{item}} dest=/etc/icinga/objects/{{item}} state=link
  with_items:
      - app-server-node-1.cfg
      - app-server-node-2.cfg
      - app-server-node-3.cfg
      - app-server-node-4.cfg
      - ci-node.cfg
      - ci-repo.cfg
      - monitoring-node.cfg
      - mongodb-node.cfg
      - checkmem.cfg

- name: remove unused icinga configuration
  sudo: yes
  raw: rm -f /etc/icinga/objects/{{item}}
  with_items:
    - localhost_icinga.cfg
    - ido2db_check_proc.cfg
    - hostgroups_icinga.cfg
    - services_icinga.cfg
    - extinfo_icinga.cfg

- sudo: yes
  copy: src={{item}} dest=/etc/icinga/{{item}} force=yes mode=0644
  with_items:
    - htpasswd.users
    - icinga.cfg
    - cgi.cfg
  notify: restart icinga