---
- apt: pkg={{item}} state=present force=yes
  with_items:
    - icinga
    - icinga-web

- file: src=/etc/nagios3/conf.d/{{item}} dest=/etc/icinga/objects/{{item}} state=link
  with_items:
      - app-server-node-1.cfg
      - app-server-node-2.cfg
      - app-server-node-3.cfg
      - app-server-node-4.cfg
      - ci-node.cfg
      - ci-repo.cfg
      - monitoring-node.cfg
      - mongodb-node.cfg

- sudo: yes
  copy: src=htpasswd.users dest=/etc/icinga/htpasswd.users force=yes mode=0644
  notify: restart icinga