---
- apt: pkg={{item}} state=present force=yes
  with_items:
    - nagios3
    - nagios-nrpe-plugin
    - ruby1.9.1-full

- sudo: yes
  copy: src={{item}} dest=/etc/nagios3/conf.d/{{item}} force=yes mode=0644
  with_items:
      - app-server-node-1.cfg
      - app-server-node-2.cfg
      - app-server-node-3.cfg
      - app-server-node-4.cfg
      - ci-node.cfg
      - ci-repo.cfg
      - elasticsearch-node.cfg
      - mongodb-node.cfg

#- sudo: yes
#  command: rm /etc/nagios3/conf.d/*_nagios2.cfg
#  ignore_errors: yes

- sudo: yes
  copy: src=htpasswd.users dest=/etc/nagios3/htpasswd.users force=yes mode=0644
  notify: restart nagios3

- sudo: yes
  raw: mkdir -p /var/log/nagios/

- sudo: yes
  raw: gem install nagira

- sudo: yes
  raw: nagira-setup config:all
