---
- apt: pkg={{item}} state=present force=yes
  with_items:
    - nagios3
    - nagios-nrpe-plugin

- sudo: yes
  copy: src={{item}} dest=/etc/nagios3/conf.d/{{item}} force=yes mode=0644
  with_items:
      - app-server-node-1.cfg
      - app-server-node-2.cfg
      - app-server-node-3.cfg
      - ci-node.cfg
      - ci-repo.cfg
      - elasticsearch-node.cfg
      - mongodb-node.cfg

- sudo: yes
  copy: src=htpasswd.users dest=/etc/nagios3/htpasswd.users force=yes mode=0644
  notify: restart nagios3