---
- apt: pkg={{item}} state=present force=yes
  with_items:
    - vim
    - mongodb-clients
    - curl
    - tree
    - htop
    - nagios-nrpe-server
    - curl
    - build-essential
    - g++
