---
- name: add sonar repository into sources list.
  apt_repository: repo='deb http://downloads.sourceforge.net/project/sonar-pkg/deb binary/' state=present

- name: update cache
  apt: update_cache=yes force=yes

- name: install sonar
  apt: pkg={{item}} state=present force=yes
  with_items:
    - sonar
    - postgresql
    - python-psycopg2

- name: create sonar db user
  sudo: yes
  sudo_user: postgres
  postgresql_user:
      name=sonar
      password=sonar
      role_attr_flags=CREATEDB,NOSUPERUSER

- name: create sonar db
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=sonar
                 encoding='UTF-8'
                 lc_collate='C'
                 lc_ctype='C'
                 template='template0'

- name: install sonar properties
  copy: src=sonar.properties dest=/opt/sonar/conf/sonar.properties mode=0755
  notify: restart sonar